### ISSUE TITLE
Error using ChatWindowView with mobile Wi-Fi hotspot

### ISSUE THREAD

**Issue by ArcherEmiya05** [livechat/chat-window-android#37]
LiveChat SDK for android works well as on Android Oreo and above but not sure why it is not working on Android M device that having its connection from a mobile Hotspot of another device. The error log seems to do with a connection issue. Here is the complete log.

`E/LiveChat Widget: failed to connect to cdn.livechatinc.com/127.0.0.1 (port 443) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
W/System.err: java.net.ConnectException: failed to connect to cdn.livechatinc.com/127.0.0.1 (port 443) after 15000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:234)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
        at java.net.Socket.connect(Socket.java:888)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
        at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
        at com.android.okhttp.Connection.connect(Connection.java:143)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.winbig88.bola.inappchat.k.a(LoadWebViewContentTask.java:64)
        at com.winbig88.bola.inappchat.k.doInBackground(LoadWebViewContentTask.java:30)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:223)
`

**Comment by sommeshEwall** [comment]
In some device alone I'm getting the below error:

> java.net.ConnectException: Connection refused


Whereas in other real devices it's working fine. Kindly let us know what is causing this problem for some of the devices alone.

**Comment by nomyzs** [comment]
Hello.
I know this is a very late response, but we’ve rewritten the library and are now using a different HTTP client. I wasn’t able to reproduce the issue, so it should no longer occur in the latest version.

Please don’t hesitate to open a new issue if you encounter any problems.
