### ISSUE TITLE
Error 'custom_mobile_settings'

### ISSUE THREAD

**Issue by pateras01** [livechat/chat-window-android#39]
Hi, error from android library version 2.1.2
This error from onError method:
	uncaught at Xp
		at Fs
		at Ns
		TypeError: Cannot read property 'custom_mobile_settings' of undefined
		at As (https://cdn.livechatinc.com/widget/static/js/iframe.c7c9ffb3.chunk.js:1:108670)
		at https://cdn.livechatinc.com/widget/static/js/iframe.c7c9ffb3.chunk.js:1:114725
		at c (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:460894)
		at Generator._invoke (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:460682)
		at Generator.forEach.e.<computed> [as next] (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:461317)
		at I (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:171012)
		at y (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:171876)
		at https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:172609
		at o (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:158116)
		at c (https://cdn.livechatinc.com/widget/static/js/2.862f655b.chunk.js:1:158266)

Any help? Thank Patrik

**Comment by nomyzs** [comment]
Hey @pateras01 !
Can you check if your group id setting is correct and it exists?
